CREATE OR REPLACE PACKAGE uuid_v7 AUTHID DEFINER AS
  -- SPDX-License-Identifier: MIT
  -- Copyright (c) 2026 Ian Woodbury
  /*
   * RFC 9562 version 7 UUIDs as RAW(16), for Oracle Database 12.2+ (built for 19c).
   *
   *    0                   1                   2                   3
   *    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   *   +---------------------------------------------------------------+
   *   |                  unix_ts_ms (48 bits, big-endian)             |
   *   |                               +-------+-----------------------+
   *   |                               | ver=7 |  sub-ms fraction (12) |
   *   +---+---------------------------+-------+-----------------------+
   *   |var|                     random (62 bits)                      |
   *   |   |                                                           |
   *   +---+-----------------------------------------------------------+
   *
   * The 12 "rand_a" bits carry a sub-millisecond clock fraction (RFC 9562
   * section 6.2, method 3 - the same choice PostgreSQL 18 makes). Within a
   * session the 60-bit timestamp is forced to be strictly increasing, so values
   * generated by one session always sort in generation order, exactly like
   * sequence.NEXTVAL. Across sessions/instances, ordering is by wall clock and
   * uniqueness rests on the 62 random bits.
   *
   * RAW compares bytewise, so ORDER BY / index order on the column is
   * chronological.
   */

  /*
   * Compiled with PLSQL_CCFLAGS (filled in by install.sql):
   *   uuid_v7_no_crypto    = &uuid_v7_no_crypto
   *   uuid_v7_coarse_clock = &uuid_v7_coarse_clock
   */

  -- Next UUIDv7. Never NULL, always 16 bytes.
  FUNCTION generate RETURN RAW PARALLEL_ENABLE;

  -- 0190A5E3... -> '0190a5e3-....' canonical 8-4-4-4-12 lower-case text.
  FUNCTION to_string(p_uuid IN RAW) RETURN VARCHAR2 DETERMINISTIC PARALLEL_ENABLE;

  -- Canonical text (hyphens optional, any case) -> RAW(16).
  FUNCTION from_string(p_text IN VARCHAR2) RETURN RAW DETERMINISTIC PARALLEL_ENABLE;

  -- The embedded creation time (millisecond precision, UTC) of a v7 UUID.
  FUNCTION timestamp_of(p_uuid IN RAW) RETURN TIMESTAMP WITH TIME ZONE
    DETERMINISTIC PARALLEL_ENABLE;
END uuid_v7;
/
